# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestEngine2.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(559, 506)
        MainWindow.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 140, 111, 31))
        self.label.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(210, 140, 151, 31))
        self.comboBox.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(380, 140, 101, 31))
        self.pushButton.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.pushButton.setObjectName("pushButton")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(210, 190, 151, 31))
        self.comboBox_2.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 190, 91, 31))
        self.label_2.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 190, 101, 31))
        self.pushButton_2.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.StudentRegister = QtWidgets.QFrame(self.centralwidget)
        self.StudentRegister.setGeometry(QtCore.QRect(0, -20, 561, 501))
        self.StudentRegister.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.StudentRegister.setFrameShadow(QtWidgets.QFrame.Raised)
        self.StudentRegister.setObjectName("StudentRegister")
        self.label_3 = QtWidgets.QLabel(self.StudentRegister)
        self.label_3.setGeometry(QtCore.QRect(130, 20, 261, 41))
        self.label_3.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 18pt \"Lucida Fax\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.StudentRegister)
        self.label_4.setGeometry(QtCore.QRect(60, 90, 81, 21))
        self.label_4.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 12pt \"Lucida Fax\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.StudentRegister)
        self.label_5.setGeometry(QtCore.QRect(60, 120, 121, 21))
        self.label_5.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 12pt \"Lucida Fax\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.StudentRegister)
        self.label_6.setGeometry(QtCore.QRect(60, 150, 81, 21))
        self.label_6.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 12pt \"Lucida Fax\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.StudentRegister)
        self.label_7.setGeometry(QtCore.QRect(60, 180, 81, 21))
        self.label_7.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 12pt \"Lucida Fax\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.StudentRegister)
        self.label_8.setGeometry(QtCore.QRect(60, 210, 81, 21))
        self.label_8.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 12pt \"Lucida Fax\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.StudentRegister)
        self.label_9.setGeometry(QtCore.QRect(60, 240, 81, 21))
        self.label_9.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 12pt \"Lucida Fax\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.StudentRegister)
        self.label_10.setGeometry(QtCore.QRect(60, 270, 81, 21))
        self.label_10.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 12pt \"Lucida Fax\";")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.StudentRegister)
        self.label_11.setGeometry(QtCore.QRect(60, 300, 81, 21))
        self.label_11.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 12pt \"Lucida Fax\";")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.StudentRegister)
        self.label_12.setGeometry(QtCore.QRect(60, 330, 81, 21))
        self.label_12.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 12pt \"Lucida Fax\";")
        self.label_12.setObjectName("label_12")
        self.lineEdit = QtWidgets.QLineEdit(self.StudentRegister)
        self.lineEdit.setGeometry(QtCore.QRect(200, 90, 151, 21))
        self.lineEdit.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 12pt \"Lucida Fax\";")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.StudentRegister)
        self.lineEdit_2.setGeometry(QtCore.QRect(200, 120, 151, 21))
        self.lineEdit_2.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 12pt \"Lucida Fax\";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.StudentRegister)
        self.lineEdit_3.setGeometry(QtCore.QRect(200, 150, 151, 21))
        self.lineEdit_3.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 12pt \"Lucida Fax\";")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.StudentRegister)
        self.lineEdit_4.setGeometry(QtCore.QRect(200, 180, 151, 21))
        self.lineEdit_4.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 12pt \"Lucida Fax\";")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.StudentRegister)
        self.lineEdit_5.setGeometry(QtCore.QRect(200, 210, 151, 21))
        self.lineEdit_5.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 12pt \"Lucida Fax\";")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.StudentRegister)
        self.lineEdit_6.setGeometry(QtCore.QRect(200, 240, 151, 21))
        self.lineEdit_6.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 12pt \"Lucida Fax\";")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.StudentRegister)
        self.lineEdit_7.setGeometry(QtCore.QRect(200, 270, 151, 21))
        self.lineEdit_7.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 12pt \"Lucida Fax\";")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.StudentRegister)
        self.lineEdit_8.setGeometry(QtCore.QRect(200, 300, 151, 21))
        self.lineEdit_8.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 12pt \"Lucida Fax\";")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.textEdit = QtWidgets.QTextEdit(self.StudentRegister)
        self.textEdit.setGeometry(QtCore.QRect(200, 330, 151, 91))
        self.textEdit.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 12pt \"Lucida Fax\";")
        self.textEdit.setObjectName("textEdit")
        self.pushButton_3 = QtWidgets.QPushButton(self.StudentRegister)
        self.pushButton_3.setGeometry(QtCore.QRect(120, 440, 91, 31))
        self.pushButton_3.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 16pt \"Lucida Fax\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.StudentRegister)
        self.pushButton_4.setGeometry(QtCore.QRect(240, 440, 91, 31))
        self.pushButton_4.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 16pt \"Lucida Fax\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.TeacherRegistration = QtWidgets.QFrame(self.StudentRegister)
        self.TeacherRegistration.setGeometry(QtCore.QRect(0, 0, 561, 501))
        self.TeacherRegistration.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TeacherRegistration.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TeacherRegistration.setObjectName("TeacherRegistration")
        self.label_13 = QtWidgets.QLabel(self.TeacherRegistration)
        self.label_13.setGeometry(QtCore.QRect(120, 50, 241, 31))
        self.label_13.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 18pt \"Lucida Fax\";")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.TeacherRegistration)
        self.label_14.setGeometry(QtCore.QRect(50, 120, 111, 21))
        self.label_14.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 12pt \"Lucida Fax\";")
        self.label_14.setObjectName("label_14")
        self.label_17 = QtWidgets.QLabel(self.TeacherRegistration)
        self.label_17.setGeometry(QtCore.QRect(50, 150, 111, 21))
        self.label_17.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 12pt \"Lucida Fax\";")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.TeacherRegistration)
        self.label_18.setGeometry(QtCore.QRect(50, 180, 111, 21))
        self.label_18.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 12pt \"Lucida Fax\";")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.TeacherRegistration)
        self.label_19.setGeometry(QtCore.QRect(50, 210, 111, 21))
        self.label_19.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 12pt \"Lucida Fax\";")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.TeacherRegistration)
        self.label_20.setGeometry(QtCore.QRect(50, 240, 111, 21))
        self.label_20.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 12pt \"Lucida Fax\";")
        self.label_20.setObjectName("label_20")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.TeacherRegistration)
        self.lineEdit_9.setGeometry(QtCore.QRect(230, 120, 151, 25))
        self.lineEdit_9.setMinimumSize(QtCore.QSize(0, 21))
        self.lineEdit_9.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 12pt \"Lucida Fax\";")
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.TeacherRegistration)
        self.lineEdit_10.setGeometry(QtCore.QRect(230, 150, 151, 25))
        self.lineEdit_10.setMinimumSize(QtCore.QSize(0, 21))
        self.lineEdit_10.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 12pt \"Lucida Fax\";")
        self.lineEdit_10.setText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.TeacherRegistration)
        self.lineEdit_11.setGeometry(QtCore.QRect(230, 180, 151, 25))
        self.lineEdit_11.setMinimumSize(QtCore.QSize(0, 21))
        self.lineEdit_11.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 12pt \"Lucida Fax\";")
        self.lineEdit_11.setText("")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.TeacherRegistration)
        self.lineEdit_12.setGeometry(QtCore.QRect(230, 210, 151, 25))
        self.lineEdit_12.setMinimumSize(QtCore.QSize(0, 21))
        self.lineEdit_12.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 12pt \"Lucida Fax\";")
        self.lineEdit_12.setText("")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.TeacherRegistration)
        self.lineEdit_13.setGeometry(QtCore.QRect(230, 240, 151, 25))
        self.lineEdit_13.setMinimumSize(QtCore.QSize(0, 21))
        self.lineEdit_13.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 12pt \"Lucida Fax\";")
        self.lineEdit_13.setText("")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.pushButton_5 = QtWidgets.QPushButton(self.TeacherRegistration)
        self.pushButton_5.setGeometry(QtCore.QRect(110, 310, 81, 31))
        self.pushButton_5.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.TeacherRegistration)
        self.pushButton_6.setGeometry(QtCore.QRect(220, 310, 81, 31))
        self.pushButton_6.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.StudentLogin = QtWidgets.QFrame(self.TeacherRegistration)
        self.StudentLogin.setGeometry(QtCore.QRect(0, 0, 561, 501))
        self.StudentLogin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.StudentLogin.setFrameShadow(QtWidgets.QFrame.Raised)
        self.StudentLogin.setObjectName("StudentLogin")
        self.label_15 = QtWidgets.QLabel(self.StudentLogin)
        self.label_15.setGeometry(QtCore.QRect(130, 60, 241, 41))
        self.label_15.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 18pt \"Lucida Fax\";")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.StudentLogin)
        self.label_16.setGeometry(QtCore.QRect(80, 140, 121, 41))
        self.label_16.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.label_16.setObjectName("label_16")
        self.label_21 = QtWidgets.QLabel(self.StudentLogin)
        self.label_21.setGeometry(QtCore.QRect(80, 190, 121, 41))
        self.label_21.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.label_21.setObjectName("label_21")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.StudentLogin)
        self.lineEdit_14.setGeometry(QtCore.QRect(210, 150, 175, 30))
        self.lineEdit_14.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.StudentLogin)
        self.lineEdit_15.setGeometry(QtCore.QRect(210, 200, 175, 30))
        self.lineEdit_15.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.pushButton_7 = QtWidgets.QPushButton(self.StudentLogin)
        self.pushButton_7.setGeometry(QtCore.QRect(110, 270, 111, 31))
        self.pushButton_7.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 16pt \"Lucida Fax\";")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.StudentLogin)
        self.pushButton_8.setGeometry(QtCore.QRect(250, 270, 111, 31))
        self.pushButton_8.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 16pt \"Lucida Fax\";")
        self.pushButton_8.setObjectName("pushButton_8")
        self.TeacheLogin = QtWidgets.QFrame(self.StudentLogin)
        self.TeacheLogin.setGeometry(QtCore.QRect(-1, -1, 561, 501))
        self.TeacheLogin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TeacheLogin.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TeacheLogin.setObjectName("TeacheLogin")
        self.label_22 = QtWidgets.QLabel(self.TeacheLogin)
        self.label_22.setGeometry(QtCore.QRect(130, 60, 221, 41))
        self.label_22.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 18pt \"Lucida Fax\";")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.TeacheLogin)
        self.label_23.setGeometry(QtCore.QRect(60, 120, 201, 31))
        self.label_23.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.TeacheLogin)
        self.label_24.setGeometry(QtCore.QRect(60, 160, 221, 31))
        self.label_24.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.TeacheLogin)
        self.label_25.setGeometry(QtCore.QRect(60, 200, 201, 31))
        self.label_25.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.TeacheLogin)
        self.label_26.setGeometry(QtCore.QRect(60, 240, 201, 31))
        self.label_26.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.label_26.setObjectName("label_26")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.TeacheLogin)
        self.lineEdit_16.setGeometry(QtCore.QRect(290, 120, 175, 25))
        self.lineEdit_16.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.lineEdit_16.setText("")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.TeacheLogin)
        self.lineEdit_17.setGeometry(QtCore.QRect(290, 160, 175, 25))
        self.lineEdit_17.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.lineEdit_17.setText("")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.TeacheLogin)
        self.lineEdit_18.setGeometry(QtCore.QRect(290, 200, 175, 25))
        self.lineEdit_18.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.lineEdit_18.setText("")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.TeacheLogin)
        self.lineEdit_19.setGeometry(QtCore.QRect(290, 240, 175, 25))
        self.lineEdit_19.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.lineEdit_19.setText("")
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.pushButton_9 = QtWidgets.QPushButton(self.TeacheLogin)
        self.pushButton_9.setGeometry(QtCore.QRect(100, 310, 91, 31))
        self.pushButton_9.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 16pt \"Lucida Fax\";")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.TeacheLogin)
        self.pushButton_10.setGeometry(QtCore.QRect(230, 310, 91, 31))
        self.pushButton_10.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 16pt \"Lucida Fax\";")
        self.pushButton_10.setObjectName("pushButton_10")
        self.StudentChooseSubject = QtWidgets.QFrame(self.TeacheLogin)
        self.StudentChooseSubject.setGeometry(QtCore.QRect(0, 0, 561, 501))
        self.StudentChooseSubject.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.StudentChooseSubject.setFrameShadow(QtWidgets.QFrame.Raised)
        self.StudentChooseSubject.setObjectName("StudentChooseSubject")
        self.comboBox_3 = QtWidgets.QComboBox(self.StudentChooseSubject)
        self.comboBox_3.setGeometry(QtCore.QRect(80, 140, 181, 31))
        self.comboBox_3.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_27 = QtWidgets.QLabel(self.StudentChooseSubject)
        self.label_27.setGeometry(QtCore.QRect(130, 50, 331, 51))
        self.label_27.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 18pt \"Lucida Fax\";")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.StudentChooseSubject)
        self.label_28.setGeometry(QtCore.QRect(400, 140, 161, 31))
        self.label_28.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.StudentChooseSubject)
        self.label_29.setGeometry(QtCore.QRect(80, 190, 281, 31))
        self.label_29.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.StudentChooseSubject)
        self.label_30.setGeometry(QtCore.QRect(80, 220, 281, 31))
        self.label_30.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.StudentChooseSubject)
        self.label_31.setGeometry(QtCore.QRect(80, 250, 281, 31))
        self.label_31.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.label_31.setObjectName("label_31")
        self.pushButton_11 = QtWidgets.QPushButton(self.StudentChooseSubject)
        self.pushButton_11.setGeometry(QtCore.QRect(220, 340, 131, 31))
        self.pushButton_11.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 14pt \"Lucida Fax\";")
        icon = QtGui.QIcon.fromTheme("dd")
        self.pushButton_11.setIcon(icon)
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_32 = QtWidgets.QLabel(self.StudentChooseSubject)
        self.label_32.setGeometry(QtCore.QRect(80, 280, 281, 31))
        self.label_32.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.label_32.setObjectName("label_32")
        self.Test = QtWidgets.QFrame(self.StudentChooseSubject)
        self.Test.setGeometry(QtCore.QRect(0, 0, 561, 501))
        self.Test.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Test.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Test.setObjectName("Test")
        self.label_33 = QtWidgets.QLabel(self.Test)
        self.label_33.setGeometry(QtCore.QRect(30, 70, 481, 31))
        self.label_33.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.label_33.setObjectName("label_33")
        self.radioButton = QtWidgets.QRadioButton(self.Test)
        self.radioButton.setGeometry(QtCore.QRect(60, 130, 121, 21))
        self.radioButton.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.Test)
        self.radioButton_2.setGeometry(QtCore.QRect(60, 170, 121, 21))
        self.radioButton_2.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.Test)
        self.radioButton_3.setGeometry(QtCore.QRect(60, 210, 121, 21))
        self.radioButton_3.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.Test)
        self.radioButton_4.setGeometry(QtCore.QRect(60, 250, 121, 21))
        self.radioButton_4.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.radioButton_4.setObjectName("radioButton_4")
        self.pushButton_12 = QtWidgets.QPushButton(self.Test)
        self.pushButton_12.setGeometry(QtCore.QRect(150, 320, 91, 31))
        self.pushButton_12.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 16pt \"Lucida Fax\";")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.Test)
        self.pushButton_13.setGeometry(QtCore.QRect(290, 320, 151, 31))
        self.pushButton_13.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.pushButton_13.setObjectName("pushButton_13")
        self.ViewScore = QtWidgets.QFrame(self.Test)
        self.ViewScore.setGeometry(QtCore.QRect(0, 0, 561, 501))
        self.ViewScore.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ViewScore.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ViewScore.setObjectName("ViewScore")
        self.label_34 = QtWidgets.QLabel(self.ViewScore)
        self.label_34.setGeometry(QtCore.QRect(70, 180, 121, 31))
        self.label_34.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 16pt \"Lucida Fax\";")
        self.label_34.setObjectName("label_34")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.ViewScore)
        self.lineEdit_20.setGeometry(QtCore.QRect(230, 180, 120, 30))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.pushButton_14 = QtWidgets.QPushButton(self.ViewScore)
        self.pushButton_14.setGeometry(QtCore.QRect(390, 30, 141, 31))
        self.pushButton_14.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 18pt \"Lucida Fax\";")
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_35 = QtWidgets.QLabel(self.ViewScore)
        self.label_35.setGeometry(QtCore.QRect(10, 100, 541, 31))
        self.label_35.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.ViewScore)
        self.label_36.setGeometry(QtCore.QRect(10, 130, 541, 31))
        self.label_36.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.ViewScore)
        self.label_37.setGeometry(QtCore.QRect(70, 230, 121, 31))
        self.label_37.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 16pt \"Lucida Fax\";")
        self.label_37.setObjectName("label_37")
        self.textEdit_2 = QtWidgets.QTextEdit(self.ViewScore)
        self.textEdit_2.setGeometry(QtCore.QRect(230, 220, 321, 161))
        self.textEdit_2.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.textEdit_2.setObjectName("textEdit_2")
        self.CreateTest = QtWidgets.QFrame(self.ViewScore)
        self.CreateTest.setGeometry(QtCore.QRect(0, 0, 551, 501))
        self.CreateTest.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CreateTest.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CreateTest.setObjectName("CreateTest")
        self.comboBox_4 = QtWidgets.QComboBox(self.CreateTest)
        self.comboBox_4.setGeometry(QtCore.QRect(40, 130, 191, 41))
        self.comboBox_4.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 16pt \"Lucida Fax\";")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.pushButton_15 = QtWidgets.QPushButton(self.CreateTest)
        self.pushButton_15.setGeometry(QtCore.QRect(250, 130, 191, 41))
        self.pushButton_15.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 16pt \"Lucida Fax\";")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.CreateTest)
        self.pushButton_16.setGeometry(QtCore.QRect(250, 270, 191, 41))
        self.pushButton_16.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 16pt \"Lucida Fax\";")
        self.pushButton_16.setObjectName("pushButton_16")
        self.label_38 = QtWidgets.QLabel(self.CreateTest)
        self.label_38.setGeometry(QtCore.QRect(40, 210, 181, 31))
        self.label_38.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.label_38.setObjectName("label_38")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.CreateTest)
        self.lineEdit_21.setGeometry(QtCore.QRect(250, 210, 190, 35))
        self.lineEdit_21.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.label_39 = QtWidgets.QLabel(self.CreateTest)
        self.label_39.setGeometry(QtCore.QRect(340, 20, 181, 31))
        self.label_39.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 16pt \"Lucida Fax\";")
        self.label_39.setObjectName("label_39")
        self.AddQuestion = QtWidgets.QFrame(self.CreateTest)
        self.AddQuestion.setGeometry(QtCore.QRect(-1, -1, 551, 501))
        self.AddQuestion.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AddQuestion.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AddQuestion.setObjectName("AddQuestion")
        self.label_40 = QtWidgets.QLabel(self.AddQuestion)
        self.label_40.setGeometry(QtCore.QRect(10, 90, 181, 51))
        self.label_40.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 16pt \"Lucida Fax\";")
        self.label_40.setObjectName("label_40")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.AddQuestion)
        self.lineEdit_22.setGeometry(QtCore.QRect(200, 90, 340, 50))
        self.lineEdit_22.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 16pt \"Lucida Fax\";")
        self.lineEdit_22.setText("")
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.label_41 = QtWidgets.QLabel(self.AddQuestion)
        self.label_41.setGeometry(QtCore.QRect(70, 170, 181, 31))
        self.label_41.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.AddQuestion)
        self.label_42.setGeometry(QtCore.QRect(70, 210, 111, 31))
        self.label_42.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.AddQuestion)
        self.label_43.setGeometry(QtCore.QRect(70, 250, 111, 31))
        self.label_43.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.AddQuestion)
        self.label_44.setGeometry(QtCore.QRect(70, 290, 111, 31))
        self.label_44.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 14pt \"Lucida Fax\";")
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.AddQuestion)
        self.label_45.setGeometry(QtCore.QRect(70, 330, 111, 51))
        self.label_45.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 16pt \"Lucida Fax\";")
        self.label_45.setObjectName("label_45")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.AddQuestion)
        self.lineEdit_23.setGeometry(QtCore.QRect(200, 170, 281, 31))
        self.lineEdit_23.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 16pt \"Lucida Fax\";")
        self.lineEdit_23.setText("")
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.AddQuestion)
        self.lineEdit_24.setGeometry(QtCore.QRect(200, 209, 281, 31))
        self.lineEdit_24.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 16pt \"Lucida Fax\";")
        self.lineEdit_24.setText("")
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.AddQuestion)
        self.lineEdit_25.setGeometry(QtCore.QRect(200, 250, 281, 31))
        self.lineEdit_25.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 16pt \"Lucida Fax\";")
        self.lineEdit_25.setText("")
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.AddQuestion)
        self.lineEdit_26.setGeometry(QtCore.QRect(200, 290, 281, 31))
        self.lineEdit_26.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 16pt \"Lucida Fax\";")
        self.lineEdit_26.setText("")
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.AddQuestion)
        self.lineEdit_27.setGeometry(QtCore.QRect(200, 340, 281, 31))
        self.lineEdit_27.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 16pt \"Lucida Fax\";")
        self.lineEdit_27.setText("")
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.pushButton_17 = QtWidgets.QPushButton(self.AddQuestion)
        self.pushButton_17.setGeometry(QtCore.QRect(200, 390, 201, 41))
        self.pushButton_17.setStyleSheet("color:rgb(85, 0, 127);\n"
"font: 75 18pt \"Lucida Fax\";")
        self.pushButton_17.setObjectName("pushButton_17")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 559, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.StudentRegister.hide()
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TestEngine"))
        self.label.setText(_translate("MainWindow", "Register As"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Choose User"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Teacher"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Student"))
        self.pushButton.setText(_translate("MainWindow", "Register"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Choose User"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Teacher"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Student"))
        self.label_2.setText(_translate("MainWindow", "Login As"))
        self.pushButton_2.setText(_translate("MainWindow", "Login"))
        self.label_3.setText(_translate("MainWindow", "Registration As "))
        self.label_4.setText(_translate("MainWindow", "Name"))
        self.label_5.setText(_translate("MainWindow", "Father\'s Name"))
        self.label_6.setText(_translate("MainWindow", "Course"))
        self.label_7.setText(_translate("MainWindow", "Stream"))
        self.label_8.setText(_translate("MainWindow", "Email"))
        self.label_9.setText(_translate("MainWindow", "Password"))
        self.label_10.setText(_translate("MainWindow", "Age"))
        self.label_11.setText(_translate("MainWindow", "Contact"))
        self.label_12.setText(_translate("MainWindow", "Address"))
        self.pushButton_3.setText(_translate("MainWindow", "SignUp"))
        self.pushButton_4.setText(_translate("MainWindow", "Clear"))
        self.label_13.setText(_translate("MainWindow", "Registration As"))
        self.label_14.setText(_translate("MainWindow", "College ID"))
        self.label_17.setText(_translate("MainWindow", "Name"))
        self.label_18.setText(_translate("MainWindow", "Email"))
        self.label_19.setText(_translate("MainWindow", "Password"))
        self.label_20.setText(_translate("MainWindow", "Contact"))
        self.pushButton_5.setText(_translate("MainWindow", "SignUp"))
        self.pushButton_6.setText(_translate("MainWindow", "Clear"))
        self.label_15.setText(_translate("MainWindow", "Login As"))
        self.label_16.setText(_translate("MainWindow", "Email"))
        self.label_21.setText(_translate("MainWindow", "Password"))
        self.pushButton_7.setText(_translate("MainWindow", "SignIn"))
        self.pushButton_8.setText(_translate("MainWindow", "Clear"))
        self.label_22.setText(_translate("MainWindow", "Login As"))
        self.label_23.setText(_translate("MainWindow", "Test Engine ID"))
        self.label_24.setText(_translate("MainWindow", "Test Engine Password"))
        self.label_25.setText(_translate("MainWindow", "Email"))
        self.label_26.setText(_translate("MainWindow", "Password"))
        self.pushButton_9.setText(_translate("MainWindow", "SignIn"))
        self.pushButton_10.setText(_translate("MainWindow", "Clear"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Choose Subject"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "C"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "C++"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Java"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "C#"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "Python"))
        self.label_27.setText(_translate("MainWindow", "Welcome to Test Engine"))
        self.label_28.setText(_translate("MainWindow", "Given Test : "))
        self.label_29.setText(_translate("MainWindow", "1. Test will be of 30 minutes"))
        self.label_30.setText(_translate("MainWindow", "1. Test will be of 30 minutes"))
        self.label_31.setText(_translate("MainWindow", "1. Test will be of 30 minutes"))
        self.pushButton_11.setText(_translate("MainWindow", "Start Test"))
        self.label_32.setText(_translate("MainWindow", "1. Test will be of 30 minutes"))
        self.label_33.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_33.setText(_translate("MainWindow", "Question : Who will be the Prime Minister of India?"))
        self.radioButton.setText(_translate("MainWindow", "Option_1"))
        self.radioButton_2.setText(_translate("MainWindow", "Option_2"))
        self.radioButton_3.setText(_translate("MainWindow", "Option_3"))
        self.radioButton_4.setText(_translate("MainWindow", "Option_4"))
        self.pushButton_12.setText(_translate("MainWindow", "Submit"))
        self.pushButton_13.setText(_translate("MainWindow", "Next Question"))
        self.label_34.setText(_translate("MainWindow", "Final Score"))
        self.pushButton_14.setText(_translate("MainWindow", "Sign out"))
        self.label_35.setText(_translate("MainWindow", "Thank You for given your precious time to give the test."))
        self.label_36.setText(_translate("MainWindow", "I Hope, you enjoyed it and learn something from us"))
        self.label_37.setText(_translate("MainWindow", "Feedback"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Choose Subject"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "C"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "C++"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "Java"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "C#"))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "Python"))
        self.pushButton_15.setText(_translate("MainWindow", "Create Test"))
        self.pushButton_16.setText(_translate("MainWindow", "Add New Subject"))
        self.label_38.setText(_translate("MainWindow", "Enter New Subject"))
        self.label_39.setText(_translate("MainWindow", "Test Created : "))
        self.label_40.setText(_translate("MainWindow", "Enter Question :"))
        self.label_41.setText(_translate("MainWindow", "Option 1 :"))
        self.label_42.setText(_translate("MainWindow", "Option 2 :"))
        self.label_43.setText(_translate("MainWindow", "Option 3 :"))
        self.label_44.setText(_translate("MainWindow", "Option 4 :"))
        self.label_45.setText(_translate("MainWindow", "Answer : "))
        self.pushButton_17.setText(_translate("MainWindow", "Add Question"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

