from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(854, 620)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget = QtWidgets.QWidget(MainWindow)
        self.widget.setObjectName("widget")
        self.title_label = QtWidgets.QLabel(self.widget)
        self.title_label.setGeometry(QtCore.QRect(140, 10, 461, 51))
        self.title_label.setStyleSheet("color:rgb(0, 0, 255);\n"
"font: 18pt \"Franklin Gothic Demi Cond\";")
        self.title_label.setObjectName("title_label")
        self.login_label = QtWidgets.QLabel(self.widget)
        self.login_label.setGeometry(QtCore.QRect(40, 140, 171, 51))
        self.login_label.setStyleSheet("font: 20pt \"Franklin Gothic Demi Cond\";")
        self.login_label.setObjectName("login_label")
        self.register_label = QtWidgets.QLabel(self.widget)
        self.register_label.setGeometry(QtCore.QRect(30, 350, 171, 51))
        self.register_label.setStyleSheet("font: 20pt \"Franklin Gothic Demi Cond\";")
        self.register_label.setObjectName("register_label")
        self.login_combo = QtWidgets.QComboBox(self.widget)
        self.login_combo.setGeometry(QtCore.QRect(270, 130, 341, 61))
        self.login_combo.setStyleSheet("font: 18pt \"Franklin Gothic Demi Cond\";")
        self.login_combo.setObjectName("login_combo")
        self.login_combo.addItem("")
        self.login_combo.addItem("")
        self.register_combo = QtWidgets.QComboBox(self.widget)
        self.register_combo.setGeometry(QtCore.QRect(270, 340, 341, 61))
        self.register_combo.setStyleSheet("font: 18pt \"Franklin Gothic Demi Cond\";")
        self.register_combo.setObjectName("register_combo")
        self.register_combo.addItem("")
        self.register_combo.addItem("")
        self.login_btn = QtWidgets.QPushButton(self.widget)
        self.login_btn.setGeometry(QtCore.QRect(650, 130, 101, 51))
        self.login_btn.setStyleSheet("font: 14pt \"Franklin Gothic Demi Cond\";")
        self.login_btn.setObjectName("login_btn")
        self.register_btn = QtWidgets.QPushButton(self.widget)
        self.register_btn.setGeometry(QtCore.QRect(650, 340, 101, 51))
        self.register_btn.setStyleSheet("font: 14pt \"Franklin Gothic Demi Cond\";")
        self.register_btn.setObjectName("register_btn")
        self.Register_frame = QtWidgets.QFrame(self.widget)
        self.Register_frame.setGeometry(QtCore.QRect(0, -10, 801, 591))
        self.Register_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Register_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Register_frame.setObjectName("Register_frame")
        self.title_label_2 = QtWidgets.QLabel(self.Register_frame)
        self.title_label_2.setGeometry(QtCore.QRect(150, 0, 461, 51))
        self.title_label_2.setStyleSheet("color:rgb(0, 0, 255);\n"
"font: 18pt \"Franklin Gothic Demi Cond\";")
        self.title_label_2.setObjectName("title_label_2")
        self.rgstrwname_lbl = QtWidgets.QLabel(self.Register_frame)
        self.rgstrwname_lbl.setGeometry(QtCore.QRect(310, 50, 261, 71))
        self.rgstrwname_lbl.setStyleSheet("color:rgb(255, 0, 0);\n"
"font: 22pt \"Franklin Gothic Demi Cond\";")
        self.rgstrwname_lbl.setObjectName("rgstrwname_lbl")
        self.clgid_lbl = QtWidgets.QLabel(self.Register_frame)
        self.clgid_lbl.setGeometry(QtCore.QRect(40, 120, 201, 61))
        self.clgid_lbl.setStyleSheet("font: 18pt \"Franklin Gothic Demi Cond\";")
        self.clgid_lbl.setObjectName("clgid_lbl")
        self.nme_lbl = QtWidgets.QLabel(self.Register_frame)
        self.nme_lbl.setGeometry(QtCore.QRect(40, 190, 201, 61))
        self.nme_lbl.setStyleSheet("font: 18pt \"Franklin Gothic Demi Cond\";")
        self.nme_lbl.setObjectName("nme_lbl")
        self.email_lbl = QtWidgets.QLabel(self.Register_frame)
        self.email_lbl.setGeometry(QtCore.QRect(40, 270, 201, 61))
        self.email_lbl.setStyleSheet("font: 18pt \"Franklin Gothic Demi Cond\";")
        self.email_lbl.setObjectName("email_lbl")
        self.pwd_lbl = QtWidgets.QLabel(self.Register_frame)
        self.pwd_lbl.setGeometry(QtCore.QRect(40, 350, 201, 61))
        self.pwd_lbl.setStyleSheet("font: 18pt \"Franklin Gothic Demi Cond\";")
        self.pwd_lbl.setObjectName("pwd_lbl")
        self.clgid_txt = QtWidgets.QLineEdit(self.Register_frame)
        self.clgid_txt.setGeometry(QtCore.QRect(270, 130, 281, 51))
        self.clgid_txt.setStyleSheet("font: 18pt \"Franklin Gothic Demi Cond\";")
        self.clgid_txt.setObjectName("clgid_txt")
        self.nme_txt = QtWidgets.QLineEdit(self.Register_frame)
        self.nme_txt.setGeometry(QtCore.QRect(270, 200, 281, 51))
        self.nme_txt.setStyleSheet("font: 18pt \"Franklin Gothic Demi Cond\";")
        self.nme_txt.setObjectName("nme_txt")
        self.email_txt = QtWidgets.QLineEdit(self.Register_frame)
        self.email_txt.setGeometry(QtCore.QRect(270, 280, 281, 51))
        self.email_txt.setStyleSheet("font: 18pt \"Franklin Gothic Demi Cond\";")
        self.email_txt.setObjectName("email_txt")
        self.pwd_txt = QtWidgets.QLineEdit(self.Register_frame)
        self.pwd_txt.setGeometry(QtCore.QRect(270, 360, 281, 51))
        self.pwd_txt.setStyleSheet("font: 18pt \"Franklin Gothic Demi Cond\";")
        self.pwd_txt.setObjectName("pwd_txt")
        self.rgstr_btn = QtWidgets.QPushButton(self.Register_frame)
        self.rgstr_btn.setGeometry(QtCore.QRect(280, 450, 151, 61))
        self.rgstr_btn.setStyleSheet("font: 16pt \"Franklin Gothic Demi Cond\";")
        self.rgstr_btn.setObjectName("rgstr_btn")
        self.sbjctinsrt_frme = QtWidgets.QFrame(self.Register_frame)
        self.sbjctinsrt_frme.setGeometry(QtCore.QRect(10, 0, 801, 601))
        self.sbjctinsrt_frme.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sbjctinsrt_frme.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sbjctinsrt_frme.setObjectName("sbjctinsrt_frme")
        self.title_label_3 = QtWidgets.QLabel(self.sbjctinsrt_frme)
        self.title_label_3.setGeometry(QtCore.QRect(120, 10, 461, 51))
        self.title_label_3.setStyleSheet("color:rgb(0, 0, 255);\n"
"font: 18pt \"Franklin Gothic Demi Cond\";")
        self.title_label_3.setObjectName("title_label_3")
        self.title_label_4 = QtWidgets.QLabel(self.sbjctinsrt_frme)
        self.title_label_4.setGeometry(QtCore.QRect(270, 70, 271, 51))
        self.title_label_4.setStyleSheet("color:rgb(255, 0, 0);\n"
"font: 24pt \"Franklin Gothic Demi Cond\";")
        self.title_label_4.setObjectName("title_label_4")
        self.label = QtWidgets.QLabel(self.sbjctinsrt_frme)
        self.label.setGeometry(QtCore.QRect(30, 190, 301, 41))
        self.label.setStyleSheet("font: 20pt \"Franklin Gothic Demi Cond\";")
        self.label.setObjectName("label")
        self.newsbjc_txt = QtWidgets.QLineEdit(self.sbjctinsrt_frme)
        self.newsbjc_txt.setGeometry(QtCore.QRect(410, 200, 271, 31))
        self.newsbjc_txt.setStyleSheet("font: 14pt \"Franklin Gothic Demi Cond\";")
        self.newsbjc_txt.setObjectName("newsbjc_txt")
        self.insbjct_btn = QtWidgets.QPushButton(self.sbjctinsrt_frme)
        self.insbjct_btn.setGeometry(QtCore.QRect(240, 340, 321, 51))
        self.insbjct_btn.setStyleSheet("font: 14pt \"Franklin Gothic Demi Cond\";")
        self.insbjct_btn.setObjectName("insbjct_btn")
        self.qstinsrt_frme = QtWidgets.QFrame(self.sbjctinsrt_frme)
        self.qstinsrt_frme.setGeometry(QtCore.QRect(-10, 10, 821, 671))
        self.qstinsrt_frme.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.qstinsrt_frme.setFrameShadow(QtWidgets.QFrame.Raised)
        self.qstinsrt_frme.setObjectName("qstinsrt_frme")
        self.title_label_5 = QtWidgets.QLabel(self.qstinsrt_frme)
        self.title_label_5.setGeometry(QtCore.QRect(100, 0, 461, 51))
        self.title_label_5.setStyleSheet("color:rgb(0, 0, 255);\n"
"font: 18pt \"Franklin Gothic Demi Cond\";")
        self.title_label_5.setObjectName("title_label_5")
        self.title_label_6 = QtWidgets.QLabel(self.qstinsrt_frme)
        self.title_label_6.setGeometry(QtCore.QRect(240, 70, 291, 51))
        self.title_label_6.setStyleSheet("color:rgb(255, 0, 0);\n"
"font: 24pt \"Franklin Gothic Demi Cond\";")
        self.title_label_6.setObjectName("title_label_6")
        self.label_11 = QtWidgets.QLabel(self.qstinsrt_frme)
        self.label_11.setGeometry(QtCore.QRect(30, 120, 261, 61))
        self.label_11.setStyleSheet("font: 18pt \"Franklin Gothic Demi Cond\";")
        self.label_11.setObjectName("label_11")
        self.qstn_txt = QtWidgets.QLineEdit(self.qstinsrt_frme)
        self.qstn_txt.setGeometry(QtCore.QRect(30, 170, 651, 61))
        self.qstn_txt.setStyleSheet("font: 14pt \"Franklin Gothic Demi Cond\";")
        self.qstn_txt.setObjectName("qstn_txt")
        self.label_12 = QtWidgets.QLabel(self.qstinsrt_frme)
        self.label_12.setGeometry(QtCore.QRect(40, 290, 141, 61))
        self.label_12.setStyleSheet("font: 14pt \"Franklin Gothic Demi Cond\";")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.qstinsrt_frme)
        self.label_13.setGeometry(QtCore.QRect(40, 350, 141, 61))
        self.label_13.setStyleSheet("font: 14pt \"Franklin Gothic Demi Cond\";")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.qstinsrt_frme)
        self.label_14.setGeometry(QtCore.QRect(40, 410, 141, 61))
        self.label_14.setStyleSheet("font: 14pt \"Franklin Gothic Demi Cond\";")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.qstinsrt_frme)
        self.label_15.setGeometry(QtCore.QRect(40, 470, 141, 61))
        self.label_15.setStyleSheet("font: 14pt \"Franklin Gothic Demi Cond\";")
        self.label_15.setObjectName("label_15")
        self.optn1_txt = QtWidgets.QLineEdit(self.qstinsrt_frme)
        self.optn1_txt.setGeometry(QtCore.QRect(140, 300, 231, 41))
        self.optn1_txt.setStyleSheet("font: 14pt \"Franklin Gothic Demi Cond\";")
        self.optn1_txt.setObjectName("optn1_txt")
        self.optn2_txt = QtWidgets.QLineEdit(self.qstinsrt_frme)
        self.optn2_txt.setGeometry(QtCore.QRect(140, 360, 231, 41))
        self.optn2_txt.setStyleSheet("font: 14pt \"Franklin Gothic Demi Cond\";")
        self.optn2_txt.setObjectName("optn2_txt")
        self.optn3_txt = QtWidgets.QLineEdit(self.qstinsrt_frme)
        self.optn3_txt.setGeometry(QtCore.QRect(140, 420, 231, 41))
        self.optn3_txt.setStyleSheet("font: 14pt \"Franklin Gothic Demi Cond\";")
        self.optn3_txt.setObjectName("optn3_txt")
        self.optn4_txt = QtWidgets.QLineEdit(self.qstinsrt_frme)
        self.optn4_txt.setGeometry(QtCore.QRect(140, 480, 231, 41))
        self.optn4_txt.setStyleSheet("font: 14pt \"Franklin Gothic Demi Cond\";")
        self.optn4_txt.setObjectName("optn4_txt")
        self.crtqst_btn = QtWidgets.QPushButton(self.qstinsrt_frme)
        self.crtqst_btn.setGeometry(QtCore.QRect(190, 540, 221, 41))
        self.crtqst_btn.setStyleSheet("font: 18pt \"Franklin Gothic Demi Cond\";")
        self.crtqst_btn.setObjectName("crtqst_btn")
        self.login_frame = QtWidgets.QFrame(self.qstinsrt_frme)
        self.login_frame.setGeometry(QtCore.QRect(0, 0, 811, 631))
        self.login_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_frame.setObjectName("login_frame")
        self.title_label_7 = QtWidgets.QLabel(self.login_frame)
        self.title_label_7.setGeometry(QtCore.QRect(110, 0, 461, 51))
        self.title_label_7.setStyleSheet("color:rgb(0, 0, 255);\n"
"font: 18pt \"Franklin Gothic Demi Cond\";")
        self.title_label_7.setObjectName("title_label_7")
        self.title_label_8 = QtWidgets.QLabel(self.login_frame)
        self.title_label_8.setGeometry(QtCore.QRect(330, 60, 291, 51))
        self.title_label_8.setStyleSheet("color:rgb(255, 0, 0);\n"
"font: 24pt \"Franklin Gothic Demi Cond\";")
        self.title_label_8.setObjectName("title_label_8")
        self.label_2 = QtWidgets.QLabel(self.login_frame)
        self.label_2.setGeometry(QtCore.QRect(90, 170, 161, 41))
        self.label_2.setStyleSheet("font: 14pt \"Franklin Gothic Demi Cond\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.login_frame)
        self.label_3.setGeometry(QtCore.QRect(90, 260, 161, 41))
        self.label_3.setStyleSheet("font: 14pt \"Franklin Gothic Demi Cond\";")
        self.label_3.setObjectName("label_3")
        self.eml_lgn_txt = QtWidgets.QLineEdit(self.login_frame)
        self.eml_lgn_txt.setGeometry(QtCore.QRect(250, 170, 231, 41))
        self.eml_lgn_txt.setStyleSheet("font: 14pt \"Franklin Gothic Demi Cond\";")
        self.eml_lgn_txt.setObjectName("eml_lgn_txt")
        self.pwd_lgn_txt = QtWidgets.QLineEdit(self.login_frame)
        self.pwd_lgn_txt.setGeometry(QtCore.QRect(250, 260, 231, 41))
        self.pwd_lgn_txt.setStyleSheet("font: 14pt \"Franklin Gothic Demi Cond\";")
        self.pwd_lgn_txt.setObjectName("pwd_lgn_txt")
        self.pushButton = QtWidgets.QPushButton(self.login_frame)
        self.pushButton.setGeometry(QtCore.QRect(240, 350, 141, 41))
        self.pushButton.setStyleSheet("font: 14pt \"Franklin Gothic Demi Cond\";")
        self.pushButton.setObjectName("pushButton")
        self.qstn_stdnt_frame = QtWidgets.QFrame(self.login_frame)
        self.qstn_stdnt_frame.setGeometry(QtCore.QRect(0, 0, 831, 601))
        self.qstn_stdnt_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.qstn_stdnt_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.qstn_stdnt_frame.setObjectName("qstn_stdnt_frame")
        self.title_label_9 = QtWidgets.QLabel(self.qstn_stdnt_frame)
        self.title_label_9.setGeometry(QtCore.QRect(150, 10, 461, 51))
        self.title_label_9.setStyleSheet("color:rgb(0, 0, 255);\n"
"font: 18pt \"Franklin Gothic Demi Cond\";")
        self.title_label_9.setObjectName("title_label_9")
        self.title_label_10 = QtWidgets.QLabel(self.qstn_stdnt_frame)
        self.title_label_10.setGeometry(QtCore.QRect(200, 70, 461, 51))
        self.title_label_10.setStyleSheet("color:rgb(255, 0, 0);\n"
"font: 28pt \"Franklin Gothic Demi Cond\";")
        self.title_label_10.setObjectName("title_label_10")
        self.label_5 = QtWidgets.QLabel(self.qstn_stdnt_frame)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 671, 61))
        self.label_5.setStyleSheet("font: 16pt \"Franklin Gothic Demi Cond\";")
        self.label_5.setObjectName("label_5")
        self.opt1 = QtWidgets.QRadioButton(self.qstn_stdnt_frame)
        self.opt1.setGeometry(QtCore.QRect(20, 220, 101, 41))
        self.opt1.setObjectName("opt1")
        self.opt2 = QtWidgets.QRadioButton(self.qstn_stdnt_frame)
        self.opt2.setGeometry(QtCore.QRect(20, 260, 91, 31))
        self.opt2.setObjectName("opt2")
        self.opt3 = QtWidgets.QRadioButton(self.qstn_stdnt_frame)
        self.opt3.setGeometry(QtCore.QRect(20, 300, 91, 31))
        self.opt3.setObjectName("opt3")
        self.opt4 = QtWidgets.QRadioButton(self.qstn_stdnt_frame)
        self.opt4.setGeometry(QtCore.QRect(20, 340, 91, 31))
        self.opt4.setObjectName("opt4")
        self.nxt_qstn_btn = QtWidgets.QPushButton(self.qstn_stdnt_frame)
        self.nxt_qstn_btn.setGeometry(QtCore.QRect(80, 390, 211, 51))
        self.nxt_qstn_btn.setStyleSheet("font: 22pt \"Franklin Gothic Demi Cond\";")
        self.nxt_qstn_btn.setObjectName("nxt_qstn_btn")
        self.title_label_9.raise_()
        self.title_label_10.raise_()
        self.label_5.raise_()
        self.opt1.raise_()
        self.opt2.raise_()
        self.opt3.raise_()
        self.opt4.raise_()
        self.nxt_qstn_btn.raise_()
        self.report_frame = QtWidgets.QFrame(self.Register_frame)
        self.report_frame.setGeometry(QtCore.QRect(0, 10, 821, 571))
        self.report_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.report_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.report_frame.setObjectName("report_frame")
        self.title_label_11 = QtWidgets.QLabel(self.report_frame)
        self.title_label_11.setGeometry(QtCore.QRect(210, 30, 461, 51))
        self.title_label_11.setStyleSheet("color:rgb(255, 0, 0);\n"
"font: 28pt \"Franklin Gothic Demi Cond\";")
        self.title_label_11.setObjectName("title_label_11")
        self.label_4 = QtWidgets.QLabel(self.report_frame)
        self.label_4.setGeometry(QtCore.QRect(40, 130, 181, 51))
        self.label_4.setStyleSheet("font: 28pt \"Franklin Gothic Demi Cond\";")
        self.label_4.setObjectName("label_4")
        self.score_txt = QtWidgets.QLineEdit(self.report_frame)
        self.score_txt.setGeometry(QtCore.QRect(250, 140, 241, 41))
        self.score_txt.setReadOnly(True)
        self.score_txt.setObjectName("score_txt")
        self.sbjct_slct_frame = QtWidgets.QFrame(self.report_frame)
        self.sbjct_slct_frame.setGeometry(QtCore.QRect(0, 0, 821, 571))
        self.sbjct_slct_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sbjct_slct_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sbjct_slct_frame.setObjectName("sbjct_slct_frame")
        self.title_label_12 = QtWidgets.QLabel(self.sbjct_slct_frame)
        self.title_label_12.setGeometry(QtCore.QRect(240, 90, 461, 51))
        self.title_label_12.setStyleSheet("color:rgb(255, 0, 0);\n"
"font: 28pt \"Franklin Gothic Demi Cond\";")
        self.title_label_12.setObjectName("title_label_12")
        self.title_label_13 = QtWidgets.QLabel(self.sbjct_slct_frame)
        self.title_label_13.setGeometry(QtCore.QRect(110, 10, 461, 51))
        self.title_label_13.setStyleSheet("color:rgb(0, 0, 255);\n"
"font: 18pt \"Franklin Gothic Demi Cond\";")
        self.title_label_13.setObjectName("title_label_13")
        self.label_6 = QtWidgets.QLabel(self.sbjct_slct_frame)
        self.label_6.setGeometry(QtCore.QRect(30, 180, 241, 41))
        self.label_6.setStyleSheet("font: 20pt \"Franklin Gothic Demi Cond\";")
        self.label_6.setObjectName("label_6")
        self.sbjct_slct_cmbo = QtWidgets.QComboBox(self.sbjct_slct_frame)
        self.sbjct_slct_cmbo.setGeometry(QtCore.QRect(290, 190, 161, 31))
        self.sbjct_slct_cmbo.setStyleSheet("font: 20pt \"Franklin Gothic Demi Cond\";")
        self.sbjct_slct_cmbo.setObjectName("sbjct_slct_cmbo")
        self.sbjct_slct_cmbo.addItem("")
        self.sbjct_slct_cmbo.addItem("")
        self.sbjct_slct_cmbo.addItem("")
        self.sbjct_slct_cmbo.addItem("")
        self.sbjct_slct_cmbo.addItem("")
        self.strt_tst_btn = QtWidgets.QPushButton(self.sbjct_slct_frame)
        self.strt_tst_btn.setGeometry(QtCore.QRect(270, 290, 261, 51))
        self.strt_tst_btn.setStyleSheet("font: 22pt \"Franklin Gothic Demi Cond\";")
        self.strt_tst_btn.setObjectName("strt_tst_btn")
        MainWindow.setCentralWidget(self.widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 854, 21))
        self.menubar.setObjectName("menubar")
        self.menuOption = QtWidgets.QMenu(self.menubar)
        self.menuOption.setObjectName("menuOption")
        self.menuLogin = QtWidgets.QMenu(self.menubar)
        self.menuLogin.setObjectName("menuLogin")
        self.menuTeacher = QtWidgets.QMenu(self.menubar)
        self.menuTeacher.setObjectName("menuTeacher")
        self.menuStudent = QtWidgets.QMenu(self.menubar)
        self.menuStudent.setObjectName("menuStudent")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionHome = QtWidgets.QAction(MainWindow)
        self.actionHome.setObjectName("actionHome")
        self.actionRegister = QtWidgets.QAction(MainWindow)
        self.actionRegister.setObjectName("actionRegister")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionTeacher = QtWidgets.QAction(MainWindow)
        self.actionTeacher.setObjectName("actionTeacher")
        self.actionStudent = QtWidgets.QAction(MainWindow)
        self.actionStudent.setObjectName("actionStudent")
        self.actionCreate_Test = QtWidgets.QAction(MainWindow)
        self.actionCreate_Test.setObjectName("actionCreate_Test")
        self.actionView_Test = QtWidgets.QAction(MainWindow)
        self.actionView_Test.setObjectName("actionView_Test")
        self.actionView_Subjects = QtWidgets.QAction(MainWindow)
        self.actionView_Subjects.setObjectName("actionView_Subjects")
        self.actionCreate_Test_2 = QtWidgets.QAction(MainWindow)
        self.actionCreate_Test_2.setObjectName("actionCreate_Test_2")
        self.actionCreate_New_Subject = QtWidgets.QAction(MainWindow)
        self.actionCreate_New_Subject.setObjectName("actionCreate_New_Subject")
        self.menuOption.addAction(self.actionHome)
        self.menuOption.addAction(self.actionRegister)
        self.menuOption.addAction(self.actionExit)
        self.menuLogin.addAction(self.actionTeacher)
        self.menuLogin.addAction(self.actionStudent)
        self.menuTeacher.addAction(self.actionCreate_Test)
        self.menuTeacher.addAction(self.actionView_Test)
        self.menuTeacher.addAction(self.actionCreate_New_Subject)
        self.menuStudent.addAction(self.actionView_Subjects)
        self.menuStudent.addAction(self.actionCreate_Test_2)
        self.menubar.addAction(self.menuOption.menuAction())
        self.menubar.addAction(self.menuLogin.menuAction())
        self.menubar.addAction(self.menuTeacher.menuAction())
        self.menubar.addAction(self.menuStudent.menuAction())

        self.Register_frame.hide()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_label.setText(_translate("MainWindow", "                               WELCOME TO APTITUDE TEST PORTAL"))
        self.login_label.setText(_translate("MainWindow", "Login As"))
        self.register_label.setText(_translate("MainWindow", "Register As"))
        self.login_combo.setItemText(0, _translate("MainWindow", "Teacher"))
        self.login_combo.setItemText(1, _translate("MainWindow", "Student"))
        self.register_combo.setItemText(0, _translate("MainWindow", "Teacher"))
        self.register_combo.setItemText(1, _translate("MainWindow", "Student"))
        self.login_btn.setText(_translate("MainWindow", "LOGIN"))
        self.register_btn.setText(_translate("MainWindow", "REGISTER"))
        self.title_label_2.setText(_translate("MainWindow", "                               WELCOME TO APTITUDE TEST PORTAL"))
        self.rgstrwname_lbl.setText(_translate("MainWindow", "Register As"))
        self.clgid_lbl.setText(_translate("MainWindow", "Enter College ID"))
        self.nme_lbl.setText(_translate("MainWindow", "Enter Your Name"))
        self.email_lbl.setText(_translate("MainWindow", "Enter Email ID"))
        self.pwd_lbl.setText(_translate("MainWindow", "Enter Your Password"))
        self.rgstr_btn.setText(_translate("MainWindow", "Register"))
        self.title_label_3.setText(_translate("MainWindow", "                               WELCOME TO APTITUDE TEST PORTAL"))
        self.title_label_4.setText(_translate("MainWindow", "SUBJECT GENERATOR"))
        self.label.setText(_translate("MainWindow", "Enter The Name Of Subject"))
        self.insbjct_btn.setText(_translate("MainWindow", "Insert Subject"))
        self.title_label_5.setText(_translate("MainWindow", "                               WELCOME TO APTITUDE TEST PORTAL"))
        self.title_label_6.setText(_translate("MainWindow", "QUESTION GENERATOR"))
        self.label_11.setText(_translate("MainWindow", "Enter Your Question"))
        self.label_12.setText(_translate("MainWindow", "Option 1"))
        self.label_13.setText(_translate("MainWindow", "Option 2"))
        self.label_14.setText(_translate("MainWindow", "Option 3"))
        self.label_15.setText(_translate("MainWindow", "Option 4"))
        self.crtqst_btn.setText(_translate("MainWindow", "Create Question"))
        self.title_label_7.setText(_translate("MainWindow", "                               WELCOME TO APTITUDE TEST PORTAL"))
        self.title_label_8.setText(_translate("MainWindow", "LOGIN"))
        self.label_2.setText(_translate("MainWindow", "Enter Email ID"))
        self.label_3.setText(_translate("MainWindow", "Enter Password"))
        self.pushButton.setText(_translate("MainWindow", "LOGIN"))
        self.title_label_9.setText(_translate("MainWindow", "                               WELCOME TO APTITUDE TEST PORTAL"))
        self.title_label_10.setText(_translate("MainWindow", "Please Attempt Carefully!!!"))
        self.label_5.setText(_translate("MainWindow", "Question : Who is the prime minister of India ?"))
        self.opt1.setText(_translate("MainWindow", "opt1"))
        self.opt2.setText(_translate("MainWindow", "opt2"))
        self.opt3.setText(_translate("MainWindow", "opt3"))
        self.opt4.setText(_translate("MainWindow", "opt4"))
        self.nxt_qstn_btn.setText(_translate("MainWindow", "Next Question"))
        self.title_label_11.setText(_translate("MainWindow", "REPORT GENERATION"))
        self.label_4.setText(_translate("MainWindow", "Final Score:"))
        self.title_label_12.setText(_translate("MainWindow", "SUBJECT SELECTION"))
        self.title_label_13.setText(_translate("MainWindow", "                               WELCOME TO APTITUDE TEST PORTAL"))
        self.label_6.setText(_translate("MainWindow", "Select Your Subject"))
        self.sbjct_slct_cmbo.setItemText(0, _translate("MainWindow", "Select Here.."))
        self.sbjct_slct_cmbo.setItemText(1, _translate("MainWindow", "Python"))
        self.sbjct_slct_cmbo.setItemText(2, _translate("MainWindow", "Java"))
        self.sbjct_slct_cmbo.setItemText(3, _translate("MainWindow", "C++"))
        self.sbjct_slct_cmbo.setItemText(4, _translate("MainWindow", "GK"))
        self.strt_tst_btn.setText(_translate("MainWindow", "Create/Start Test"))
        self.menuOption.setTitle(_translate("MainWindow", "Options"))
        self.menuLogin.setTitle(_translate("MainWindow", "Login"))
        self.menuTeacher.setTitle(_translate("MainWindow", "Teacher"))
        self.menuStudent.setTitle(_translate("MainWindow", "Student"))
        self.actionHome.setText(_translate("MainWindow", "Home"))
        self.actionRegister.setText(_translate("MainWindow", "Register"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionTeacher.setText(_translate("MainWindow", "Teacher"))
        self.actionStudent.setText(_translate("MainWindow", "Student"))
        self.actionCreate_Test.setText(_translate("MainWindow", "Create Test"))
        self.actionView_Test.setText(_translate("MainWindow", "View Test"))
        self.actionView_Subjects.setText(_translate("MainWindow", "View Tests"))
        self.actionCreate_Test_2.setText(_translate("MainWindow", "Create New Test"))
        self.actionCreate_New_Subject.setText(_translate("MainWindow", "Create New Subject"))

        self.register_btn.clicked.connect(self.registerUser)

    def registerUser(self):
        self.Register_frame.show()

    def loginUser(self):
        pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

